# Site settings
title:  March for Science Madison
email:  sciencemarchmsn@gmail.com
description: "March for Science Madison Wisconsin Science March Madison MSN April 22, 2017 Earth Day 2017 The March for Science is a celebration of our passion for science and a call to support and safeguard the scientific community."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: ScienceMarchMSN
facebook_username: MADISONsciencemarch

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
protocols:
    fb_image: "/img/color_atom.png"
    fb_image_width: 128
    fb_image_height: 141
    fb_image_type: "image/png"

    twitter_image: "/img/color_atom.png"
